//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeveloperTestNet5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeveloperTestNet5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSL/TLS.
        /// </summary>
        internal static string Enum_EncryptionOptions_SSL {
            get {
                return ResourceManager.GetString("Enum_EncryptionOptions_SSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTTLS.
        /// </summary>
        internal static string Enum_EncryptionOptions_STARTTLS {
            get {
                return ResourceManager.GetString("Enum_EncryptionOptions_STARTTLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unencrypted.
        /// </summary>
        internal static string Enum_EncryptionOptions_Unencrypted {
            get {
                return ResourceManager.GetString("Enum_EncryptionOptions_Unencrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMAP.
        /// </summary>
        internal static string Enum_MailServerTypes_IMAP {
            get {
                return ResourceManager.GetString("Enum_MailServerTypes_IMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP3.
        /// </summary>
        internal static string Enum_MailServerTypes_POP3 {
            get {
                return ResourceManager.GetString("Enum_MailServerTypes_POP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password..
        /// </summary>
        internal static string ERR_InputNoPassword {
            get {
                return ResourceManager.GetString("ERR_InputNoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid port..
        /// </summary>
        internal static string ERR_InputNoPort {
            get {
                return ResourceManager.GetString("ERR_InputNoPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a server..
        /// </summary>
        internal static string ERR_InputNoServer {
            get {
                return ResourceManager.GetString("ERR_InputNoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid username..
        /// </summary>
        internal static string ERR_InputNoUser {
            get {
                return ResourceManager.GetString("ERR_InputNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string VM_Date {
            get {
                return ResourceManager.GetString("VM_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string VM_From {
            get {
                return ResourceManager.GetString("VM_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string VM_Language {
            get {
                return ResourceManager.GetString("VM_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string VM_Server {
            get {
                return ResourceManager.GetString("VM_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Type:.
        /// </summary>
        internal static string VM_ServerType {
            get {
                return ResourceManager.GetString("VM_ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string VM_Start {
            get {
                return ResourceManager.GetString("VM_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string VM_Subject {
            get {
                return ResourceManager.GetString("VM_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string VM_Summary {
            get {
                return ResourceManager.GetString("VM_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Mail App.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
